-- =============================================================================
-- Migration 014: AI Reply Agent + A/B Testing Auto-Optimize + Voice Triggers
-- =============================================================================
-- Features from competitive research:
-- 1. AI reply agent with sub-5-min response (DIFFERENTIATOR #1)
-- 2. A/B testing auto-optimization (DIFFERENTIATOR #2)
-- 3. Voice-triggered email sequences (WHITESPACE #1)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. AI Reply Drafts (generated by AI for manual review/send)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_reply_drafts (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  reply_message_id      UUID NOT NULL REFERENCES reply_messages(id) ON DELETE CASCADE,
  lead_id               UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  campaign_id           UUID REFERENCES campaigns(id) ON DELETE SET NULL,
  -- Draft content
  draft_subject         VARCHAR(500),
  draft_body            TEXT NOT NULL,
  -- AI metadata
  ai_provider           VARCHAR(50) NOT NULL DEFAULT 'anthropic',
  ai_model              VARCHAR(100) NOT NULL DEFAULT 'claude-sonnet-4-6',
  confidence_score      DECIMAL(3,2) DEFAULT NULL
                          CHECK (confidence_score BETWEEN 0.00 AND 1.00),
  -- Sentiment analysis of original reply
  original_sentiment    VARCHAR(20) DEFAULT 'neutral'
                          CHECK (original_sentiment IN ('positive', 'neutral', 'negative', 'objection')),
  intent_category       VARCHAR(50) DEFAULT 'general'
                          CHECK (intent_category IN ('interested', 'not_interested', 'meeting_request', 'more_info', 'objection', 'unsubscribe', 'general')),
  -- Status
  status                VARCHAR(20) NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'reviewed', 'approved', 'sent', 'rejected')),
  reviewed_by           UUID REFERENCES users(id),
  reviewed_at           TIMESTAMP,
  sent_at               TIMESTAMP,
  -- Timestamps
  created_at            TIMESTAMP DEFAULT NOW(),
  updated_at            TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_reply_drafts_org ON ai_reply_drafts(organization_id);
CREATE INDEX IF NOT EXISTS idx_ai_reply_drafts_status ON ai_reply_drafts(status);
CREATE INDEX IF NOT EXISTS idx_ai_reply_drafts_reply ON ai_reply_drafts(reply_message_id);
CREATE INDEX IF NOT EXISTS idx_ai_reply_drafts_lead ON ai_reply_drafts(lead_id);
CREATE INDEX IF NOT EXISTS idx_ai_reply_drafts_campaign ON ai_reply_drafts(campaign_id);

-- ---------------------------------------------------------------------------
-- 2. AI Reply Agent Settings (per-organization)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_reply_agent_settings (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  -- Mode
  mode                  VARCHAR(20) NOT NULL DEFAULT 'manual'
                          CHECK (mode IN ('manual', 'autopilot', 'hybrid')),
  -- Autopilot settings
  auto_send_threshold   DECIMAL(3,2) NOT NULL DEFAULT 0.85
                          CHECK (auto_send_threshold BETWEEN 0.00 AND 1.00),
  max_auto_replies_per_day INTEGER NOT NULL DEFAULT 50,
  -- Response rules
  respond_to_positive   BOOLEAN NOT NULL DEFAULT TRUE,
  respond_to_neutral    BOOLEAN NOT NULL DEFAULT TRUE,
  respond_to_negative   BOOLEAN NOT NULL DEFAULT FALSE,
  respond_to_objection  BOOLEAN NOT NULL DEFAULT TRUE,
  -- Business hours
  business_hours_only   BOOLEAN NOT NULL DEFAULT TRUE,
  business_start_time   TIME NOT NULL DEFAULT '09:00:00',
  business_end_time     TIME NOT NULL DEFAULT '17:00:00',
  timezone              VARCHAR(50) NOT NULL DEFAULT 'UTC',
  -- Tone and style
  tone                  VARCHAR(50) NOT NULL DEFAULT 'professional'
                          CHECK (tone IN ('professional', 'friendly', 'casual', 'formal', 'assertive')),
  max_response_length     INTEGER NOT NULL DEFAULT 200,
  include_signature     BOOLEAN NOT NULL DEFAULT TRUE,
  -- CTA preferences
  preferred_cta         VARCHAR(50) NOT NULL DEFAULT 'schedule_call'
                          CHECK (preferred_cta IN ('schedule_call', 'reply_question', 'visit_website', 'no_cta')),
  -- Timestamps
  created_at            TIMESTAMP DEFAULT NOW(),
  updated_at            TIMESTAMP DEFAULT NOW(),
  -- Unique per org
  CONSTRAINT ai_reply_agent_settings_org_unique UNIQUE (organization_id)
);

-- ---------------------------------------------------------------------------
-- 3. Voice-Triggered Sequences (WHITESPACE #1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voice_trigger_rules (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  campaign_id           UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  name                  VARCHAR(200) NOT NULL,
  description           TEXT,
  -- Trigger conditions
  trigger_intent        VARCHAR(50) NOT NULL
                          CHECK (trigger_intent IN ('interested', 'meeting_request', 'call_me', 'qualified', 'any_reply')),
  trigger_keywords      TEXT[] DEFAULT '{}',
  min_confidence_score  DECIMAL(3,2) NOT NULL DEFAULT 0.70
                          CHECK (min_confidence_score BETWEEN 0.00 AND 1.00),
  -- Action
  action_type           VARCHAR(50) NOT NULL DEFAULT 'call'
                          CHECK (action_type IN ('call', 'email', 'both')),
  -- Call settings (for Vapi.ai)
  call_script_template  TEXT,
  vapi_assistant_id     VARCHAR(255),
  vapi_phone_number_id  VARCHAR(255),
  -- Email follow-up (if action_type includes email)
  email_template_id     UUID REFERENCES email_templates(id) ON DELETE SET NULL,
  email_delay_minutes   INTEGER NOT NULL DEFAULT 30,
  -- Cooldown
  cooldown_hours        INTEGER NOT NULL DEFAULT 24,
  max_triggers_per_day  INTEGER NOT NULL DEFAULT 10,
  -- Status
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  triggers_today        INTEGER NOT NULL DEFAULT 0,
  triggers_total        INTEGER NOT NULL DEFAULT 0,
  calls_made_total      INTEGER NOT NULL DEFAULT 0,
  -- Timestamps
  created_at            TIMESTAMP DEFAULT NOW(),
  updated_at            TIMESTAMP DEFAULT NOW(),
  last_triggered_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_voice_trigger_rules_org ON voice_trigger_rules(organization_id);
CREATE INDEX IF NOT EXISTS idx_voice_trigger_rules_campaign ON voice_trigger_rules(campaign_id);
CREATE INDEX IF NOT EXISTS idx_voice_trigger_rules_active ON voice_trigger_rules(is_active);

-- ---------------------------------------------------------------------------
-- 4. Voice Trigger Executions (log of triggered calls/emails)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS voice_trigger_executions (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  voice_trigger_rule_id UUID NOT NULL REFERENCES voice_trigger_rules(id) ON DELETE CASCADE,
  lead_id               UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  reply_message_id      UUID REFERENCES reply_messages(id) ON DELETE SET NULL,
  -- Execution details
  action_type           VARCHAR(50) NOT NULL,
  status                VARCHAR(20) NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'calling', 'completed', 'failed', 'skipped')),
  -- Call details
  vapi_call_id          VARCHAR(255),
  call_result           VARCHAR(50),
  call_transcript       TEXT,
  call_recording_url    VARCHAR(500),
  -- Email details
  email_sent_id         UUID,
  -- Timestamps
  created_at            TIMESTAMP DEFAULT NOW(),
  completed_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_voice_trigger_executions_rule ON voice_trigger_executions(voice_trigger_rule_id);
CREATE INDEX IF NOT EXISTS idx_voice_trigger_executions_lead ON voice_trigger_executions(lead_id);

-- ---------------------------------------------------------------------------
-- 5. A/B Test Enhancements (auto-optimization, multi-variant)
-- ---------------------------------------------------------------------------
ALTER TABLE ab_tests ADD COLUMN IF NOT EXISTS auto_optimize_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ab_tests ADD COLUMN IF NOT EXISTS winner_selection_method VARCHAR(20) DEFAULT 'manual'
  CHECK (winner_selection_method IN ('manual', 'auto_open_rate', 'auto_click_rate', 'auto_reply_rate', 'auto_conversion_rate'));
ALTER TABLE ab_tests ADD COLUMN IF NOT EXISTS auto_optimize_after_hours INTEGER NOT NULL DEFAULT 24;
ALTER TABLE ab_tests ADD COLUMN IF NOT EXISTS confidence_threshold DECIMAL(3,2) NOT NULL DEFAULT 0.95
  CHECK (confidence_threshold BETWEEN 0.50 AND 0.999);
ALTER TABLE ab_tests ADD COLUMN IF NOT EXISTS traffic_allocation JSONB DEFAULT '{}'; -- { variant_id: percentage }

ALTER TABLE ab_variants ADD COLUMN IF NOT EXISTS current_traffic_share DECIMAL(5,2) NOT NULL DEFAULT 100.00
  CHECK (current_traffic_share BETWEEN 0.00 AND 100.00);
ALTER TABLE ab_variants ADD COLUMN IF NOT EXISTS is_winner BOOLEAN NOT NULL DEFAULT FALSE;

-- ---------------------------------------------------------------------------
-- 6. Deliverability Advisor Scores (per-organization, per-day)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deliverability_scores (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  smtp_account_id       UUID REFERENCES smtp_accounts(id) ON DELETE CASCADE,
  brand_id              UUID REFERENCES brands(id) ON DELETE CASCADE,
  -- Score components (0-100 each)
  overall_score         INTEGER NOT NULL
                          CHECK (overall_score BETWEEN 0 AND 100),
  auth_score            INTEGER NOT NULL DEFAULT 0, -- SPF/DKIM/DMARC
  reputation_score      INTEGER NOT NULL DEFAULT 0, -- Domain/IP reputation
  engagement_score      INTEGER NOT NULL DEFAULT 0, -- Open/click/reply rates
  infrastructure_score  INTEGER NOT NULL DEFAULT 0, -- Warmup, dedicated IP, tracking domain
  content_score         INTEGER NOT NULL DEFAULT 0, -- Spam words, formatting
  -- Detailed metrics
  metrics_snapshot      JSONB DEFAULT '{}',
  -- Recommendations
  recommendations       TEXT[] DEFAULT '{}',
  -- Date
  scored_at             TIMESTAMP DEFAULT NOW(),
  score_date            DATE NOT NULL DEFAULT CURRENT_DATE,
  -- Unique per org+date+smtp
  CONSTRAINT deliverability_scores_unique UNIQUE (organization_id, score_date, smtp_account_id)
);

CREATE INDEX IF NOT EXISTS idx_deliverability_scores_org ON deliverability_scores(organization_id);
CREATE INDEX IF NOT EXISTS idx_deliverability_scores_date ON deliverability_scores(score_date);
CREATE INDEX IF NOT EXISTS idx_deliverability_scores_smtp ON deliverability_scores(smtp_account_id);

-- ---------------------------------------------------------------------------
-- 7. Migration tracking
-- ---------------------------------------------------------------------------
INSERT INTO _migrations (filename) VALUES ('014_ai_reply_voice_triggers.sql')
ON CONFLICT DO NOTHING;
